-- SQL Script to Insert Dummy Data into the Blogging Platform Database
-- Assumptions:
-- - Database is PostgreSQL or MySQL compatible (based on SQLDelete annotations).
-- - Timestamps use CURRENT_TIMESTAMP for created_at and updated_at.
-- - deleted_at is NULL initially, is_deleted is FALSE.
-- - Passwords are stored as plain text for dummy purposes (in real scenarios, hash them).
-- - Enums are stored as strings (e.g., UserRole as 'ADMIN' or 'USER', EReview as 'ONE', 'TWO', etc.).
-- - Generating a large dataset: 20 users, 30 posts, 20 tags, multiple post-tag links, 50 reviews, 100 comments (including nested ones).

-- Step 1: Insert Users (20 users: 2 admins, 18 regular users)
INSERT INTO users (created_at, updated_at, deleted_at, is_deleted, firstName, lastName, username, email, password, role)
VALUES
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'Admin', 'One', 'admin1', 'admin1@example.com', 'password123', 'ADMIN'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'Admin', 'Two', 'admin2', 'admin2@example.com', 'password123', 'ADMIN'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'User', 'One', 'user1', 'user1@example.com', 'pass1', 'USER'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'User', 'Two', 'user2', 'user2@example.com', 'pass2', 'USER'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'User', 'Three', 'user3', 'user3@example.com', 'pass3', 'USER'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'User', 'Four', 'user4', 'user4@example.com', 'pass4', 'USER'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'User', 'Five', 'user5', 'user5@example.com', 'pass5', 'USER'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'User', 'Six', 'user6', 'user6@example.com', 'pass6', 'USER'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'User', 'Seven', 'user7', 'user7@example.com', 'pass7', 'USER'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'User', 'Eight', 'user8', 'user8@example.com', 'pass8', 'USER'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'User', 'Nine', 'user9', 'user9@example.com', 'pass9', 'USER'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'User', 'Ten', 'user10', 'user10@example.com', 'pass10', 'USER'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'User', 'Eleven', 'user11', 'user11@example.com', 'pass11', 'USER'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'User', 'Twelve', 'user12', 'user12@example.com', 'pass12', 'USER'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'User', 'Thirteen', 'user13', 'user13@example.com', 'pass13', 'USER'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'User', 'Fourteen', 'user14', 'user14@example.com', 'pass14', 'USER'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'User', 'Fifteen', 'user15', 'user15@example.com', 'pass15', 'USER'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'User', 'Sixteen', 'user16', 'user16@example.com', 'pass16', 'USER'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'User', 'Seventeen', 'user17', 'user17@example.com', 'pass17', 'USER'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'User', 'Eighteen', 'user18', 'user18@example.com', 'pass18', 'USER');

-- Step 2: Insert Tags (20 tags)
INSERT INTO tags (created_at, updated_at, deleted_at, is_deleted, name)
VALUES
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'Tech'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'Programming'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'Java'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'SpringBoot'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'AI'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'MachineLearning'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'DataScience'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'WebDev'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'Frontend'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'Backend'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'DevOps'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'Cloud'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'Security'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'Blockchain'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'IoT'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'MobileDev'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'Gaming'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'OpenSource'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'Career'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 'Tutorials');

-- Step 3: Insert Posts (30 posts, authored by various users)
-- Assuming user IDs start from 1 to 20 as inserted above.
INSERT INTO posts (created_at, updated_at, deleted_at, is_deleted, author_id, title, body)
VALUES
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 1, 'Introduction to Java', 'This is a beginner guide to Java programming.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 3, 'Spring Boot Basics', 'Learn the fundamentals of Spring Boot.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 4, 'AI in Everyday Life', 'How AI impacts our daily routines.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 5, 'Machine Learning Models', 'Overview of popular ML models.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 6, 'Data Science Tools', 'Best tools for data scientists.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 7, 'Web Development Trends', 'Latest trends in web dev.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 8, 'Frontend Frameworks', 'Comparison of React, Vue, Angular.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 9, 'Backend Best Practices', 'Tips for efficient backend development.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 10, 'DevOps Essentials', 'Key concepts in DevOps.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 11, 'Cloud Computing Intro', 'Basics of cloud services.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 12, 'Cybersecurity Tips', 'Protecting your data online.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 13, 'Blockchain Explained', 'What is blockchain technology?'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 14, 'IoT Applications', 'Real-world uses of IoT.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 15, 'Mobile App Development', 'Building apps for Android and iOS.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 16, 'Game Development with Unity', 'Getting started with Unity engine.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 17, 'Contributing to Open Source', 'How to get involved in OSS projects.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 18, 'Career in Tech', 'Advice for tech job seekers.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 19, 'Java Tutorials', 'Advanced Java topics.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 20, 'Spring Security', 'Implementing security in Spring apps.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 1, 'AI Ethics', 'Discussing ethical concerns in AI.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 3, 'ML Algorithms', 'Deep dive into algorithms.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 4, 'Big Data', 'Handling large datasets.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 5, 'Responsive Design', 'Making websites mobile-friendly.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 6, 'API Development', 'Building RESTful APIs.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 7, 'CI/CD Pipelines', 'Setting up continuous integration.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 8, 'AWS Services', 'Overview of Amazon Web Services.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 9, 'Hacking Prevention', 'Common security vulnerabilities.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 10, 'Crypto Basics', 'Introduction to cryptocurrencies.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 11, 'Smart Home IoT', 'Building smart home systems.'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 12, 'Flutter for Mobile', 'Cross-platform app development.');

-- Step 4: Insert Post-Tag Links (Multiple tags per post, around 60 links for variety)
-- Assuming post IDs 1-30, tag IDs 1-20.
INSERT INTO post_tags (post_id, tag_id)
VALUES
    (1, 3), (1, 2), (1, 1),
    (2, 4), (2, 3), (2, 10),
    (3, 5), (3, 1),
    (4, 6), (4, 5),
    (5, 7), (5, 6),
    (6, 8), (6, 1),
    (7, 9), (7, 8),
    (8, 10), (8, 9),
    (9, 11), (9, 10),
    (10, 12), (10, 11),
    (11, 13), (11, 12),
    (12, 14), (12, 13),
    (13, 15), (13, 14),
    (14, 16), (14, 15),
    (15, 17), (15, 16),
    (16, 18), (16, 17),
    (17, 19), (17, 18),
    (18, 20), (18, 19),
    (19, 3), (19, 20),
    (20, 4), (20, 13),
    (21, 5), (21, 6),
    (22, 6), (22, 7),
    (23, 7), (23, 8),
    (24, 8), (24, 9),
    (25, 9), (25, 10),
    (26, 10), (26, 11),
    (27, 11), (27, 12),
    (28, 12), (28, 13),
    (29, 13), (29, 14),
    (30, 14), (30, 15),
    (1, 4), (2, 5), (3, 6), (4, 7), (5, 8), (6, 9), (7, 10), (8, 11), (9, 12), (10, 13),
    (11, 14), (12, 15), (13, 16), (14, 17), (15, 18), (16, 19), (17, 20), (18, 1), (19, 2), (20, 3);

-- Step 5: Insert Reviews (50 reviews across posts, by various users)
-- Rate uses enum strings: 'ONE', 'TWO', 'THREE', 'FOUR', 'FIVE'.
INSERT INTO reviews (created_at, updated_at, deleted_at, is_deleted, post_id, user_id, rate)
VALUES
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 1, 3, 'FIVE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 1, 4, 'FOUR'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 1, 5, 'THREE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 6, 'FIVE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 7, 'FOUR'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 3, 8, 'FIVE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 3, 9, 'TWO'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 4, 10, 'ONE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 4, 11, 'FIVE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 5, 12, 'FOUR'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 5, 13, 'THREE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 6, 14, 'FIVE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 6, 15, 'FOUR'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 7, 16, 'THREE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 7, 17, 'TWO'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 8, 18, 'ONE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 8, 19, 'FIVE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 9, 20, 'FOUR'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 9, 1, 'THREE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 10, 2, 'FIVE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 10, 3, 'FOUR'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 11, 4, 'FIVE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 11, 5, 'THREE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 12, 6, 'TWO'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 12, 7, 'ONE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 13, 8, 'FIVE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 13, 9, 'FOUR'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 14, 10, 'THREE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 14, 11, 'FIVE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 15, 12, 'FOUR'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 15, 13, 'THREE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 16, 14, 'TWO'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 16, 15, 'ONE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 17, 16, 'FIVE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 17, 17, 'FOUR'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 18, 18, 'THREE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 18, 19, 'FIVE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 19, 20, 'FOUR'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 19, 1, 'THREE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 20, 2, 'TWO'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 20, 3, 'ONE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 21, 4, 'FIVE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 21, 5, 'FOUR'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 22, 6, 'THREE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 22, 7, 'FIVE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 23, 8, 'FOUR'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 23, 9, 'THREE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 24, 10, 'TWO'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 24, 11, 'ONE'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 25, 12, 'FIVE');

-- Step 6: Insert Comments (100 comments, including nested ones)
-- Some comments have parent_comment_id for replies. Assuming comment IDs will auto-generate from 1 onwards.
-- First, insert top-level comments, then replies.
INSERT INTO comments (created_at, updated_at, deleted_at, is_deleted, post_id, user_id, body, parent_comment_id)
VALUES
    -- Top-level comments for post 1 (10 comments)
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 3, 'Great intro!', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 4, 'Very helpful.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 5, 'Needs more examples.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 6, 'Excellent!', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 7, 'I learned a lot.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 8, 'Thanks for sharing.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 9, 'Good job.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 10, 'Interesting read.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 11, 'Well written.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 12, 'Appreciate it.', NULL),

    -- Replies for post 1 (e.g., replying to comment IDs 1-10)
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 13, 'I agree!', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 14, 'Me too.', 1),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 15, 'Add code snippets.', 1),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 16, 'Yes, please.', 1),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 17, 'Thanks!', 1),

    -- Top-level for post 2 (5 comments)
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 3, 'Awesome tutorial.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 4, 'Clear explanation.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 5, 'Helped me a lot.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 6, 'Great content.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 7, 'Keep it up.', NULL),

    -- Replies for post 2
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 8, 'Totally agree.', 16),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 2, 9, 'More please.', 16),

    -- Continue for other posts similarly to reach 100 total
    -- Top-level for post 3-30 (distribute to make ~100 total)
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 3, 8, 'Insightful.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 3, 9, 'Love it.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 3, 10, 'Useful info.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 4, 11, 'Well done.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 4, 12, 'Thanks.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 4, 13, 'Informative.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 5, 14, 'Great post.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 5, 15, 'Appreciate.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 5, 16, 'Good read.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 6, 17, 'Excellent.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 6, 18, 'Helpful.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 6, 19, 'Thanks a lot.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 7, 20, 'Nice.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 7, 1, 'Cool.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 7, 2, 'Super.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 8, 3, 'Fantastic.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 8, 4, 'Awesome.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 8, 5, 'Brilliant.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 9, 6, 'Top notch.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 9, 7, 'Quality content.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 9, 8, 'Well explained.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 10, 9, 'Loved it.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 10, 10, 'Very good.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 10, 11, 'Impressive.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 11, 12, 'Solid.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 11, 13, 'Reliable info.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 11, 14, 'Thanks!', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 12, 15, 'Great job.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 12, 16, 'Keep going.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 12, 17, 'Inspiring.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 13, 18, 'Educational.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 13, 19, 'Valuable.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 13, 20, 'Perfect.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 14, 1, 'Spot on.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 14, 2, 'Right on.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 14, 3, 'Accurate.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 15, 4, 'Detailed.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 15, 5, 'Thorough.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 15, 6, 'Comprehensive.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 16, 7, 'Engaging.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 16, 8, 'Captivating.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 16, 9, 'Interesting.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 17, 10, 'Motivating.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 17, 11, 'Encouraging.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 17, 12, 'Uplifting.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 18, 13, 'Practical.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 18, 14, 'Actionable.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 18, 15, 'Useful.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 19, 16, 'Advanced.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 19, 17, 'Expert level.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 19, 18, 'Deep dive.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 20, 19, 'Secure tips.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 20, 20, 'Important.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 20, 1, 'Must read.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 21, 2, 'Ethical discussion.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 21, 3, 'Thought provoking.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 21, 4, 'Relevant.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 22, 5, 'Algorithm insights.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 22, 6, 'Detailed.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 22, 7, 'Helpful.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 23, 8, 'Big data tips.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 23, 9, 'Scalable.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 23, 10, 'Efficient.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 24, 11, 'Design best practices.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 24, 12, 'Responsive.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 24, 13, 'Mobile first.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 25, 14, 'API design.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 25, 15, 'RESTful.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 25, 16, 'Secure APIs.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 26, 17, 'CI/CD setup.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 26, 18, 'Automation.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 26, 19, 'Pipelines.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 27, 20, 'AWS overview.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 27, 1, 'Cloud services.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 27, 2, 'Scalable cloud.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 28, 3, 'Vuln fixes.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 28, 4, 'Security tips.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 28, 5, 'Prevention.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 29, 6, 'Crypto intro.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 29, 7, 'Blockchain basics.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 29, 8, 'Digital currency.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 30, 9, 'Smart homes.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 30, 10, 'IoT devices.', NULL),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 30, 11, 'Connected living.', NULL),

    -- Additional replies to fill up to 100 (e.g., replying to earlier comments)
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 3, 12, 'Yes!', 23),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 3, 13, 'Absolutely.', 23),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 4, 14, 'More details?', 26),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 4, 15, 'Agreed.', 26),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 5, 16, 'Thanks.', 29),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 5, 17, 'Helpful reply.', 29),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 6, 18, 'Good point.', 32),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 6, 19, 'I concur.', 32),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 7, 20, 'Nice addition.', 35),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 7, 1, 'Well said.', 35),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 8, 2, 'Spot on.', 38),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 8, 3, 'Exactly.', 38),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 9, 4, 'Great insight.', 41),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 9, 5, 'Thanks for that.', 41),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, FALSE, 10, 6, 'Useful.', 44);
-- Note: Adjust parent_comment_id based on actual auto-generated IDs in your DB. This script assumes sequential IDs starting from 1.
-- If running in a real DB, query for IDs or use subqueries. For dummy purposes, this provides the structure.